### ISSUE TITLE
Missing support for viewBox

### ISSUE THREAD

**Issue by JangoBrick** [JangoBrick/php-svg#20]

**Comment by cyberhobo** [comment]
Are you working on this? I was just looking for it, happy to help or test.

**Comment by JangoBrick** [comment]
It's a bit hard to pin down the exact strategy for implementing this without breaking all sorts of things, but yes, I am working on it (kind of). I'll try to get this done in the next few days. If you've got any thoughts on it, I'm always happy to hear them! :)

**Comment by cyberhobo** [comment]
Unfortunately I'm not coming at it with much experience. My intention is to
use it to simulate "cropping", which I think would only require an
interface to read and write the attribute on the SVG tag. I don't have a
sense of the repercussions of this on other components, but I'm happy to
try my use case and see what happens if you want to share a branch.

**Comment by JangoBrick** [comment]
Setters and getters for arbitrary node attributes are supported since a few versions already. Methods in the form of `getHeight()` or `setX($x)` are only for convenience.

You should be able to achieve what you need similarly to this:

```php
use JangoBrick\SVG\SVGImage;

$image = SVGImage::fromFile('./path/to/file.svg');

$doc = $image->getDocument();
$doc->setAttribute('viewBox', '0 0 200 200');

header('Content-Type: image/svg+xml');
echo $image;
```

**Comment by cyberhobo** [comment]
Thanks, I'll do that! I'll keep an eye on this issue as well to see what
you're up to.

**Comment by JangoBrick** [comment]
I've published the [viewbox branch](https://github.com/JangoBrick/php-svg/tree/viewbox), with basic support for the `viewBox` attribute in rasterization. It seems to behave correctly, but additional verification would be nice. Note that `preserveAspectRatio` is _not_ yet dealt with.

**Comment by cyberhobo** [comment]
I wrote [a quick test](https://gist.github.com/cyberhobo/1845e68063224e5cee69298a11355401) and got the output viewBox I expected. (There were artifacts from rendering paths, but I'm guessing that's a rasterization challenge - I haven't played much with that yet.)
